export const QUESTION_FETCH_VIEW = 'QUESTION_FETCH_VIEW';
export const QUESTION_CHANGE_VIEW = 'QUESTION_CHANGE_VIEW';
export const QUESTION_UPDATE_FORM = 'QUESTION_UPDATE_FORM';

export const QUESTION_FETCH_RESULT = 'QUESTION_FETCH_RESULT';
export const QUESTION_FETCH_RESULT_SUCCESS = 'QUESTION_FETCH_RESULT_SUCCESS';
export const QUESTION_FETCH_RESULT_ERROR = 'QUESTION_FETCH_RESULT_ERROR';